config/routes.rb
Kilt::Engine.routes.draw do
  
  root 'kilt#index'
  
  get     '/'              => 'kilt#index',    :as => 'home'
  get     '/:types'        => 'kilt#list',     :as => 'list'
  get     '/:types/new'    => 'kilt#new',      :as => 'new_object'
  post    '/:types'        => 'kilt#create',   :as => 'create_object'
  get     '/:types/:slug'  => 'kilt#edit',     :as => 'edit_object'
  post    '/:types/:slug'  => 'kilt#update',   :as => 'update_object'
  delete  '/:types/:slug'  => 'kilt#delete',   :as => 'delete_object'
  
end

app/controllers/kilt/kilt_controller.rb
module Kilt
  class KiltController < ActionController::Base
    layout 'kilt/cms'
    protect_from_forgery
    before_filter :ensure_config
    before_filter :authorize
    before_filter :show_default_creds_warning
    
    # Show all the object types
    def index
      @types = {}
      type_names = Kilt.types
      type_names.each do |type|
        if Kilt.send(type).name != nil
          @types[type] = Kilt.send(type).name
        else
          @types[type] = type.pluralize.capitalize
        end
      end
    end
  
    # Show the list of items for a specific object type
    def list
      @type = params[:types].singularize
      @objects = Kilt.send(@type.pluralize).order('name')
    end
  
    # Create a new object
    def new
      @type = params[:types].singularize
      @object = Kilt::Object.new(@type)
    end
  
    # Post back a new object
    def create
      type = params[:types].singularize
      
      # Get the params
      p = params[type]
      
      # Ensure we have a name
      if p['name'] == ''
        flash[:error] = "Name is required"
        redirect_to new_object_path(type.pluralize)
      else
        # Create an object and fill it with the values passed in by the form
        object = Kilt::Object.new(type)
        object.fill(p)
        
        # Call Kilt's update method
        if Kilt.create(object)
          flash[:notice] = "#{Kilt::Formatting.singular_name_of(type)} successfully updated"
          redirect_to edit_object_path(type.pluralize, object.slug)
        else
          flash[:error] = "Couldn't save #{Kilt::Formatting.singular_name_of(type)}"
          redirect_to new_object_path(type.pluralize)
        end
      end
      
    end
  
    # View/Edit a specific object
    def edit
      @type = params[:types].singularize
      @slug = params[:slug]
      @object = Kilt.get(@slug)
    end
  
    # Update an object
    def update
      type = params[:types].singularize
      slug = params[:slug]
      
      # Get the params
      p = params[type]
      
      # Ensure we have a name
      if p['name'] == ''
        flash[:error] = "Name is required"
        redirect_to edit_object_path(type.pluralize, slug)
      else
        # Create an object and fill it with the values passed in by the form
        object = Kilt.get(slug)
        object.fill(p)
      
        # Call Kilt's update method
        if Kilt.update(slug, object)
          flash[:notice] = "#{Kilt::Formatting.singular_name_of(type)} successfully updated"
        else
          flash[:error] = "Couldn't save #{Kilt::Formatting.singular_name_of(type)}"
        end
      
        # redirect to the edit screen
        redirect_to edit_object_path(type.pluralize, object.slug)
      end
    end
  
    # Delete an object
    def delete
      type = params[:types].singularize
      slug = params[:slug]
      object = Kilt.get(slug)
      
      # Call Kilt's update method
      if Kilt.delete(slug)
        flash[:notice] = "#{Kilt::Formatting.singular_name_of(type)} successfully deleted"
      else
        flash[:error] = "Couldn't delete #{Kilt::Formatting.singular_name_of(type)}"
      end
      
      # redirect to the list screen
      redirect_to list_path(type.pluralize)
    end
    
    private
    
    def ensure_config
      unless Kilt::Utils.config_is_valid?
        lines = []
        lines << '<pre>'
        lines << 'The Kilt gem has been installed, but you haven\'t configured it yet.'
        lines << 'Start configuring Kilt by running the following command:'
        lines << ''
        lines << '   rails g kilt:backend'
        lines << ''
        lines << 'Then open config/kilt/config.yml and config/kilt/creds.yml, add your database information, define your data model, start Rails, and visit http://&lt;your_app&gt;/admin'
        lines << '</pre>'
        render :text => lines.join("\n")
      end
    end
    
    def authorize
      if Kilt.config.auth && Kilt.config.auth.username && Kilt.config.auth.password
        authenticate_or_request_with_http_basic('Authorization Required') do |username, password|
          username == Kilt.config.auth.username && password == Kilt.config.auth.password
        end
      else
        true
      end
    end

    def show_default_creds_warning
      @show_default_creds_warning = Kilt.config.auth && Kilt.config.auth.username && Kilt.config.auth.password &&
                                    Kilt.config.default_auth && Kilt.config.default_auth.username && Kilt.config.default_auth.password &&
                                    Kilt.config.auth.username == Kilt.config.default_auth.username &&
                                    Kilt.config.auth.password == Kilt.config.default_auth.password
    end
    
  end
end

app/views/kilt/form/_boolean.html.erb
<div class="form-input boolean">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <input id="<%= "boolean-#{index}" %>" name="<%= "#{object.type}[#{field_name}]" %>" type="hidden" />
    <input id="<%= "boolean-dummy-#{index}" %>" type="checkbox" class="checkbox" />
</div>

<script type="text/javascript">

    // Set the initial value
    var boolean_<%= index %>_value = "<%= object["#{field_name}"] %>";
    if(boolean_<%= index %>_value == "true") {
        $('#boolean-<%= index %>').attr('value', 'true');
        $('#boolean-dummy-<%= index %>').attr('checked', 'true');
    } else {
        $('#boolean-<%= index %>').attr('value', 'false');
    }
    
    // Handle the check action
    $('#boolean-dummy-<%= index %>').on("change", function(e) {
        $('#boolean-<%= index %>').attr('value', $(this).is(":checked"));
    });

</script>

app/views/kilt/form/_datetime.html.erb
<div class="form-input text datetime">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <input name="<%= "#{object.type}[#{field_name}]" %>" type="text" value="<%= object["#{field_name}"] %>" class="datepicker">
</div>

app/views/kilt/form/_default.html.erb
<div class="form-input text">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <input name="<%= "#{object.type}[#{field_name}]" %>" type="text" value="<%= object["#{field_name}"] %>">
</div>

app/views/kilt/form/_html.html.erb
<div class="form-input">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <textarea class="html" name="<%= "#{object.type}[#{field_name}]" %>"><%= object["#{field_name}"] %></textarea>
</div>

app/views/kilt/form/_image.html.erb
<div class="form-input text">
    <label><%= Kilt::Utils.deslugify field_name %></label>

    <% if object["#{field_name}"] && object["#{field_name}"] != '' %>
        <div id="image-container-<%= index %>">
            <div id="image-<%= index %>">
                <%= image_tag Kilt::Utils.download_location('image', object["#{field_name}"]), :width => '100%' %>
            </div>
            <div>
                <a id="image-reset-<%= index%>" class="button delete <% if !object["#{field_name}"] || object["#{field_name}"] == "" %>hidden<% end %>">Reset/remove image</a>
            </div>
        </div>
    <% end %>

    <div id="image-placeholder-<%= index %>" class="<% if object["#{field_name}"] && object["#{field_name}"] != "" %>hidden<% end %>">
        <input id="image-input-<%= index%>" name="<%= "#{object.type}[#{field_name}]" %>" type="file" accept="image/*" />
        <div id="image-tip-<%= index %>" class="tip">
            Only images of type PNG, JPEG, and GIF can be uploaded.
        </div>
    </div>

    <input id="image-hidden-<%= index%>" name="<%= "#{object.type}[#{field_name}-hidden]" %>" type="hidden" />

</div>

<script type="text/javascript">

    // Remove the video
    $('#image-reset-<%= index %>').on("click", function(e) {
        $('#image-placeholder-<%= index %>').removeClass('hidden');
        $('#image-hidden-<%= index %>').val('clear');
        $('#image-reset-<%= index %>').addClass('hidden');
        $('#image-<%= index %>').hide();
        $('#image-container-<%= index %>').addClass('hidden');
    });

</script>

<style>
    #image-container-<%= index %> {
        background: #efefef;
        display: inline-block;
        min-width: 50%;
        padding: 10px 10px;
    }

    #image-container-<%= index %>.hidden {
        display: none;
    }

    #image-reset-<%= index %>,
    #image-placeholder-<%= index %>,
    #image-tip-<%= index %>{
        display: auto;
    }

    #image-reset-<%= index %> {
        background: #fff;
        color: #ddd;
        margin-top: 4px;
    }

        #image-reset-<%= index %>:hover {
            background: #e74c3c;
        }

    #image-reset-<%= index %>.hidden,
    #image-placeholder-<%= index %>.hidden,
    #image-tip-<%= index %>.hidden {
        display: none;
    }
</style>

app/views/kilt/form/_longtext.html.erb
<div class="form-input longtext">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <textarea name="<%= "#{object.type}[#{field_name}]" %>"><%= object["#{field_name}"] %></textarea>
</div>

app/views/kilt/form/_vimeo.html.erb
<div class="form-input text vimeo">
    <label><%= Kilt::Utils.deslugify field_name %></label>

    <%# Keep the actual value in a hidden field %>
    <input id="<%= "vimeo-#{index}" %>" name="<%= "#{object.type}[#{field_name}]" %>" type="hidden" value="<%= object["#{field_name}"] %>">

    <div id="vimeo-container-<%= index %>" class="<% if !(object["#{field_name}"] && object["#{field_name}"] != "") %>hidden<% end %>">
        <div id="vimeo-placeholder-<%= index %>">
            <%# Show the video if we have it %>
            <div id="vimeo-placeholder-<%= index%>">
                <% if object["#{field_name}"] && object["#{field_name}"] != "" %>
                    <iframe src="//player.vimeo.com/video/<%= object["#{field_name}"] %>?title=0&amp;byline=0&amp;portrait=0&amp;color=dedede" width="100%" height="315" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                <% end %>
            </div>
            <div>
                <a id="vimeo-reset-<%= index%>" class="button delete <% if !object["#{field_name}"] || object["#{field_name}"] == "" %>hidden<% end %>">Reset/remove video</a>
            </div>
        </div>
    </div>
    <div>
        <input id="<%= "vimeo-input-#{index}" %>" type="text" <% if object["#{field_name}"] && object["#{field_name}"] != "" %>class="hidden"<% end %> placeholder="Paste or enter a Vimeo video URL here">
    </div>
</div>

<script type="text/javascript">

    // Utility function
    function vimeo_parser_<%= index%>(url){
        var match = url.match(/http:\/\/(www\.)?vimeo.com\/(\d+)($|\/)/);
        if (match){
            return match[2];
        } else {
            return false;
        }
    }

    // Act accordingly when we can successfully get a vimeo id
    $('#vimeo-input-<%= index %>').bind("change keyup", function(e) {
        val = vimeo_parser_<%= index%>($(this).val());
        if(val != false) {
            // Inject an iFrame with the vimeo video
            var $iframe = $('<iframe width="100%" height="315" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>');
            $iframe.attr('src', '//player.vimeo.com/video/' + val + '?title=0&byline=0&portrait=0&color=dedede');
            $('#vimeo-placeholder-<%= index %>').html($iframe);

            // Show the reset button
            $('#vimeo-reset-<%= index %>').removeClass('hidden');

            // Set the hidden field value
            $('#vimeo-<%= index %>').val(val);

            // Hide the text input
            $(this).addClass('hidden');
            $('#vimeo-container-<%= index %>').removeClass('hidden');
        }
    });

    // Remove the video
    $('#vimeo-reset-<%= index %>').on("click", function(e) {
        $('#vimeo-placeholder-<%= index %>').html('');
        $('#vimeo-reset-<%= index %>').addClass('hidden');
        $('#vimeo-<%= index %>').val('');
        $('#vimeo-input-<%= index %>').val('').removeClass('hidden');
        $('#vimeo-container-<%= index %>').addClass('hidden');
    });

</script>

<style>
    #vimeo-container-<%= index %> {
        background: #efefef;
        display: inline-block;
        min-width: 50%;
        padding: 10px 10px;
    }

    #vimeo-container-<%= index %>.hidden {
        display: none;
    }

    #vimeo-reset-<%= index %> {
        background: #fff;
        color: #ddd;
        margin-top: 4px;
    }

        #vimeo-reset-<%= index %>:hover {
            background: #e74c3c;
        }

    #vimeo-reset-<%= index %>,
    #vimeo-input-<%= index %> {
        display: auto;
    }

    #vimeo-reset-<%= index %>.hidden,
    #vimeo-input-<%= index %>.hidden {
        display: none;
    }
</style>

app/views/kilt/form/boolean.html.erb
<div class="form-input boolean">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <input id="<%= "boolean-#{index}" %>" name="<%= "#{object.type}[#{field_name}]" %>" type="hidden" />
    <input id="<%= "boolean-dummy-#{index}" %>" type="checkbox" class="checkbox" />
</div>

<script type="text/javascript">

    // Set the initial value
    var boolean_<%= index %>_value = "<%= object["#{field_name}"] %>";
    if(boolean_<%= index %>_value == "true") {
        $('#boolean-<%= index %>').attr('value', 'true');
        $('#boolean-dummy-<%= index %>').attr('checked', 'true');
    } else {
        $('#boolean-<%= index %>').attr('value', 'false');
    }
    
    // Handle the check action
    $('#boolean-dummy-<%= index %>').on("change", function(e) {
        $('#boolean-<%= index %>').attr('value', $(this).is(":checked"));
    });

</script>

app/views/kilt/form/datetime.html.erb
<div class="form-input text datetime">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <input name="<%= "#{object.type}[#{field_name}]" %>" type="text" value="<%= object["#{field_name}"] %>" class="datepicker">
</div>

app/views/kilt/form/longtext.html.erb
<div class="form-input longtext">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <textarea name="<%= "#{object.type}[#{field_name}]" %>"><%= object["#{field_name}"] %></textarea>
</div>

app/views/kilt/form/number.html.erb
<div class="form-input text number">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <input id="number-<%= index %>" name="<%= "#{object.type}[#{field_name}]" %>" type="text" value="<%= object["#{field_name}"] %>" />
</div>

<script type="text/javascript">
    $('#number-<%= index %>').keypress(function(e) {
        var charCode = e.which;

        // Only allow numbers and decimals
        if (charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }

        // Don't allow a second decimal
        if (charCode == 46 && $(this).val().replace(/[^.]/g, "").length > 0) {
            return false;
        }

        // Otherwise return true
        return true;
    });
</script>

app/views/kilt/form/select_one.html.erb
<div class="form-input text">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <select name="<%= "#{object.type}[#{field_name}]" %>">
        <% options.split("|").each do |option| %>
            <% if option == object["#{field_name}"] %>
                <option value="<%= option %>" selected><%= option %></option>
            <% else %> 
                <option value="<%= option %>"><%= option %></option>
            <% end %>
        <% end %>
    </select>
</div>

app/views/kilt/form/text.html.erb
<div class="form-input text">
    <label><%= Kilt::Utils.deslugify field_name %></label>
    <input name="<%= "#{object.type}[#{field_name}]" %>" type="text" value="<%= object["#{field_name}"] %>">
</div>

app/views/kilt/form/youtube.html.erb
<div class="form-input text youtube">
    <label><%= Kilt::Utils.deslugify field_name %></label>

    <%# Keep the actual value in a hidden field %>
    <input id="<%= "youtube-#{index}" %>" name="<%= "#{object.type}[#{field_name}]" %>" type="hidden" value="<%= object["#{field_name}"] %>">

    <div id="youtube-container-<%= index %>" class="<% if !(object["#{field_name}"] && object["#{field_name}"] != "") %>hidden<% end %>">
        <%# Show the video if we have it %>
        <div id="youtube-placeholder-<%= index%>">
            <% if object["#{field_name}"] && object["#{field_name}"] != "" %>
                <iframe width="100%" height="315" src="//www.youtube.com/embed/<%= object["#{field_name}"] %>" frameborder="0" allowfullscreen></iframe>
            <% end %>
        </div>
        <div>
            <a id="youtube-reset-<%= index%>" class="button delete <% if !object["#{field_name}"] || object["#{field_name}"] == "" %>hidden<% end %>">Reset/remove video</a>
        </div>
    </div>
    <div>
        <input id="<%= "youtube-input-#{index}" %>" type="text" <% if object["#{field_name}"] && object["#{field_name}"] != "" %>class="hidden"<% end %> placeholder="Paste or enter a YouTube video URL here">
    </div>
</div>

<script type="text/javascript">

    // Utility function
    function youtube_parser_<%= index%>(url){
        var match = url.match(/^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/);
        if (match && match[2].length == 11){
            return match[2];
        } else {
            return false;
        }
    }

    // Act accordingly when we can successfully get a youtube id
    $('#youtube-input-<%= index %>').bind("change keyup", function(e) {
        val = youtube_parser_<%= index%>($(this).val());
        if(val != false) {
            // Inject an iFrame with the YouTube video
            var $iframe = $('<iframe width="100%" height="315" frameborder="0" allowfullscreen />');
            $iframe.attr('src', '//www.youtube.com/embed/' + val);
            $('#youtube-placeholder-<%= index %>').html($iframe);

            // Show the reset button
            $('#youtube-reset-<%= index %>').removeClass('hidden');

            // Set the hidden field value
            $('#youtube-<%= index %>').val(val);

            // Hide the text input
            $(this).addClass('hidden');
            $('#youtube-container-<%= index %>').removeClass('hidden');
        }
    });

    // Remove the video
    $('#youtube-reset-<%= index %>').on("click", function(e) {
        $('#youtube-placeholder-<%= index %>').html('');
        $('#youtube-reset-<%= index %>').addClass('hidden');
        $('#youtube-<%= index %>').val('');
        $('#youtube-input-<%= index %>').val('').removeClass('hidden');
        $('#youtube-container-<%= index %>').addClass('hidden');
    });

</script>

<style>
    #youtube-container-<%= index %> {
        background: #efefef;
        display: inline-block;
        min-width: 50%;
        padding: 10px 10px;
    }

    #youtube-container-<%= index %>.hidden {
        display: none;
    }

    #youtube-reset-<%= index %> {
        background: #fff;
        color: #ddd;
        margin-top: 4px;
    }

        #youtube-reset-<%= index %>:hover {
            background: #e74c3c;
        }

    #youtube-reset-<%= index %>,
    #youtube-input-<%= index %> {
        display: auto;
    }

    #youtube-reset-<%= index %>.hidden,
    #youtube-input-<%= index %>.hidden {
        display: none;
    }
</style>

app/views/kilt/kilt/_field_setup.html.erb
<% Kilt.all_used_fields.each do |field| %>
  <% begin %>
    <%= render partial: "kilt/form/#{field}_#{type}" %>
  <% rescue %>
  <% end %>
<% end %>

app/views/kilt/kilt/_form.html.erb
<div class="wr">

    <% 
        singular = Kilt::Formatting.singular_name_of @type
        plural   = Kilt::Formatting.plural_name_of @type
    %>
    
    <div class="page-actions">
        <h2><%= @object['name'] || "New #{singular}" %> 
            <% if @object['name'] %>
                <small>Type: <%= singular %></small>
            <% end %>
        </h2>

        <%= link_to "← Back to #{plural}", list_path(@type), :class => 'button back newline' %>
        <%= link_to "New #{singular}", new_object_path(@type), :class => 'button back newline' if !@object.empty? %>
    </div>

    <% if flash[:error] -%>
        <p class="error"><%= flash[:error] %></p>
    <% end %>

    <% if flash[:notice] -%>
        <p class="notice"><%= flash[:notice] %></p>
    <% end %>

    <%= form_tag @path, :method => "post", :multipart => true do %>

        <% @object.fields.each_with_index do |(key, value), index| %>
            <%= Kilt::Form.render_field(self, {
                                                key: key,
                                                value: value,
                                                object: @object,
                                                index: index
                                              } ) %>
        <% end %>

        <div class="form-input actions">
            <input type="submit" class="submit button save" value="Save">
        </div>

    <% end%>

</div>

app/views/kilt/kilt/edit.html.erb
<% @path = update_object_path(@type.pluralize, @slug) %>
<%= render :partial => 'form' %>

app/views/kilt/kilt/index.html.erb
<div class="wr">
    <ul class="object-list">
        <% @types.each do |type, _| %>
            <% name = Kilt::Formatting.plural_name_of(type) %>
            <li><%= link_to name, list_path(type.pluralize) %></li>
        <% end %>
    </ul>
</div>

app/views/kilt/kilt/list.html.erb
<div class="wr">

    <% 
        singular = Kilt::Formatting.singular_name_of @type
        plural   = Kilt::Formatting.plural_name_of @type
    %>

    <div class="page-actions">
        <h3><%= plural %></h3>
        <%= link_to "New #{singular}", new_object_path(@type.singularize), :class => 'button' %>
    </div>

    <!-- todo: search by title -->

    <% if flash[:error] -%>
        <p class="error"><%= flash[:error] %></p>
    <% end %>

    <% if flash[:notice] -%>
        <p class="notice"><%= flash[:notice] %></p>
    <% end %>

    <% if @objects.empty? %>

        No <%= plural %> found.

    <% else %>

        <table>
            <thead>
                <tr>
                    <th class="title"><h4>Name</h4></th>
                    <th class="updated"><h4>Last Updated</h4></th>
                    <th class="created"><h4>Created</h4></th>
                    <th class="actions"></th>
                </tr>
            </thead>
            <tbody>

                <% @objects.each do |object| %>

                    <tr>
                        <td class="title">
                            <%= link_to object['name'], edit_object_path(@type.pluralize, object['slug']), :class => 'edit' %>
                        </td>
                        <td class="updated">
                            <% if object['updated_at'] %>
                                <%= distance_of_time_in_words_to_now(object['updated_at'].to_datetime) %> ago
                            <% end %>
                        </td>
                        <td class="created">
                            <% if object['created_at'] %>
                                <%= distance_of_time_in_words_to_now(object['created_at'].to_datetime) %> ago
                            <% end %>
                        </td>
                        <td class="actions">
                            <%= link_to 'Edit', edit_object_path(@type.pluralize, object['slug']), :class => 'button edit' %>
                            <%= link_to 'Delete', delete_object_path(@type.pluralize, object['slug']), :class => 'button delete', :method => 'delete', :data => {:confirm => "Are you sure you want to delete this #{Kilt::Formatting.singular_name_of(@type)}?" } %>
                        </td>
                    </tr>
                <% end %>

                <!-- todo: pagination -->

            </tbody>

        </table>

    <% end %>

</div>

app/views/kilt/kilt/new.html.erb
<% @path = create_object_path(@type.pluralize) %>
<%= render :partial => 'form' %>

app/views/layouts/kilt/cms.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="utf-8">
        <title><%= Kilt.config.name %></title>
        
        <link href='http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
        <%= stylesheet_link_tag "kilt/application", :media => "all" %>
        
        <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.js" %>
        <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/codemirror/3.19.0/mode/xml/xml.min.js" %>
        <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/javascript/javascript.min.js" %>
        <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/codemirror/3.19.0/mode/css/css.min.js" %>
        <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/htmlmixed/htmlmixed.min.js" %>
        
        <%= javascript_include_tag "kilt/application" %>
        
        <%= csrf_meta_tags %>

        <%= render partial: 'kilt/kilt/field_setup', locals: { type: 'head' } %>
</head>
<body>
    
    <%= render :partial => 'layouts/kilt/cms/menu' %>
    
    <section class="body">
        <%= render :partial => 'layouts/kilt/cms/default_creds_warning' %>
        <%= yield %>
    </section>
    
    <footer>
        <div class="icon">
            <%= link_to image_tag('kilt/logo.png'), 'http://github.com/kilt-cms/kilt-cms', :target => '_blank' %>
        </div>
    </footer>
    
    <%= render partial: 'kilt/kilt/field_setup', locals: { type: 'foot' } %>
</body>
</html>

app/views/layouts/kilt/cms/_default_creds_warning.html.erb
<% return unless @show_default_creds_warning %>
<div class="wr">
  <h4 style="text-align:center;color:red">You are still using the default username/password.<br />We strongly recommend that you change it in your config/kilt/creds.yml file.</h4>
</div>

app/views/layouts/kilt/cms/_menu.html.erb
<header class="hd">
    <div class="wr">
        <h6><a href="<%= kilt_engine.root_path %>"><%= Kilt.config.name %></a></h6>
        <a class="button dashboard home" href="<%= kilt_engine.root_path %>">Admin Home</a>
    </div>
</header>